name: Bug Report
description: Report any bugs or issues
labels: ["pending"]
body:
  - type: markdown
    attributes:
      value: |
        * Please check [Online Documentation](https://www.amebaiot.com/en/amebaz2/)
        * Please check and search in [List of closed issues](https://github.com/Ameba-AIoT/amazon-freertos/issues?q=is%3Aissue+is%3Aclosed)
        * Please check and search in [List of existing issues](https://github.com/Ameba-AIoT/amazon-freertos/issues?q=is%3Aopen+is%3Aissue)
        * If still experiencing the issue, please provide as many details as possible below about your hardware, environment setup and software.
  - type: input
    id: br-boards
    attributes:
      label: Boards
      description: What is the hardware/module using?
      placeholder: eg. AmebaZ2, AmebaD, AmebaDPlus, AmebaPro or AmebaPRo2...
    validations:
      required: true
  - type: textarea
    id: br-ex-hw
    attributes:
      label: External Hardware
      description: Any external hardware that Ameba board attached to?
      placeholder: eg. third-party extension, plain module on breadboard, customized hardware... please attach a photo if necessary.
    validations:
       required: true
  - type: textarea
    id: br-addon-hw
    attributes:
      label: Hardware Configuration
      description: Is anything else attached to the Hardware?
      placeholder: eg. sensors, peripherals...
    validations:
      required: true
